#!/usr/bin/env bash
set -e
[ -n "$BOOTSTRAP_DEBUG" ] && set -x

banner()  { printf -- "-----> $*\n"; }
log()     { printf -- "       $*\n"; }
warn()    { printf -- ">>>>>> $*\n"; }
fail()    { printf -- "\nERROR: $*\n" ; exit 1 ; }

banner "Checking for Packer"
if ! command -v packer >/dev/null ; then
  fail "An installation of Packer could not be found, please install a package"
fi

if [[ "$(packer --version)" < "Packer v0.2.3" ]] ; then
  fail "Only Packer versions 0.2.3 and up are supported, please update"
fi

banner 'All ready!'
