#!/usr/bin/env bash
set -e
[ -n "$BOOTSTRAP_DEBUG" ] && set -x

banner()  { printf -- "-----> $*\n"; }
log()     { printf -- "       $*\n"; }
warn()    { printf -- ">>>>>> $*\n"; }
fail()    { printf -- "\nERROR: $*\n" ; exit 1 ; }

packer_min_version="0.3.4"

banner "Checking for Packer (>= $packer_min_version)"
if ! command -v packer >/dev/null ; then
  fail "An installation of Packer could not be found, please install a package"
fi

if [[ "$(packer --version)" < "Packer v$packer_min_version" ]] ; then
  fail "Only Packer versions $packer_min_version and up are supported, please update"
fi

banner "Checking for Ruby (>= 1.8)"
if ! command -v ruby >/dev/null ; then
  fail "Ruby not found on PATH and is required for script/build, please install"
fi

banner 'All ready!'
